<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Il2CppDumper.Cli</RootNamespace>
    <AssemblyName>il2cppdumper</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishSelfContained>true</PublishSelfContained>
    <PublishTrimmed Condition="'$(Configuration)' == 'Release'">true</PublishTrimmed>
    <TrimMode Condition="'$(Configuration)' == 'Release'">partial</TrimMode>
    <EnableCompressionInSingleFile Condition="'$(Configuration)' == 'Release'">true</EnableCompressionInSingleFile>
    <DebugType Condition="'$(Configuration)' == 'Release'">None</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Il2CppDumper.Application/Il2CppDumper.Application.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <TrimmerRootAssembly Include="Il2CppDumper.Core" />
  </ItemGroup>
</Project>
